apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBbj1Qa1Dftw63HIBkNN33tC99mdvuB7RBnaXpwGOywhYAzYFoMFRS1mENZyGEBX/GoJ+pHhq05TN3meD6AnERQ7rUVgKVMLRgQyQmaOlmnyZ7idS25slxHS8uvEsXS4Wo4Sihs23ecqM7DWgeMFVBuSxWU2wPhaFM7pRmmNJqCfaeyflbK/hPYw0v7VwoxG+JRfoXqu/F9DqUcRIcxKjUZBz8NnQzkbIbccgT5oavp9cj5O2/rXp1HzS2Gr8k3sbh1axfp1ZJuvOaJXRs8p8Z+COx+L3yYZ67f44DqnjU+79SD3ZOWpdLWyKZXk2d70jp3TQfR81DiMJcK6+nCEsNDRjLzh8HvU+1gPSCfHsLWnw1CJImt7Ao4aI2acxqH2Vem682KpzH1jlViPrGya87LArCohsvGW1BqylJLuF9V4sQSJ9ZBHwgrog3mvF6msQz5zjLzOCNXXaQlvVtEpGZqlvTx/NWltgkDLuP3Mx/GEAe7Qk5IPK/6T3KDdSpW/dbc5+eJTWKEUtgoKQpva1wlZX+LEfyZBV/yPXg30N2v/TI2ACLFDV/u4Zl8fZze8X74zPUOk9ZD830pYjnBieuJrHh4XSyIMbf3kXQi3jKA2PvFVDYNlLa+usDaPZv5pdrYhXMIrT28irFs9uyd2P7Dg4sOi2iBk0iKb2Bb4IXmXW6aLE+MYXKlCESSAFP+KOKGyQpu0Mkxu/CZ3sMUnuLyi/QE43JPNkUx0qBaI5G4fyrr+APgrW+QFIQxkaX4E/kj4vYCaQaDYm0BJrfiM3bzqxnugRMbtZtGz14fXupcMu7osK7OfWzOBvcaKnxSPJiIq1LH0KQfDyNYhXqJCGO4hJcqiT0zk8C9KJdC
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: discord-url
      namespace: flux-system

