---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: flux-cd
  secretRef:
    name: discord-url

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notifications
  namespace: flux-system
spec:
  summary: "prod-001"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: '*'
    - kind: GitRepository
      name: '*'

    - kind: Kustomization
      name: '*'

    - kind: HelmChart
      name: '*'
    - kind: HelmRelease
      name: '*'

