apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: primary-credentials-metrics
  namespace: monitoring
spec:
  encryptedData:
    password: AgBW3MaoA0qr3JvE6TmS7oJ3BV5hr+3fdjxERQkUC9v4opXPPRhgh7OBKgNa71kVbopIgy6MOuXFHfAOB6T8rFpRxpevu1ZptADlXkD0ch8pT4hfjhHbGPFZp6hLWuFok6Vx6aA0Xfqc8ltYNxIOtY6hwi+jx/WgYax83Tqz+zEGJJiywqT9DsqAiBWREu3RW0TmfYL2PbzM8nd1S2dJuUCAlhAil2GLAAE3QEzGooNDsslaWdj2gdM5XwYGoz7bT/qDqYnHJH0mDcqPgB2fGPvuyvrS3i0ros5Z4FYE3Bt3dXm6xLvaUxyz87MAa0WSVJhEMDnUX42SinrpFwW7OMpUfzIlOJn6k0wxRrbVwOFiQjr0UklxqO2Lnc62ekxWQdoQ9XA0V3VCMzUytzGmD1EgYOGjjmkgIsQlTHDWcoK3k1F6zask/AadkHZQ0Yi1ST4fWK9IPLlzAtDt7EA0uXq3DtfZRjtPXFmRie6thZ+zilLzm3UXBFxwSSphNdMPx1Cy3QxBqIUOok8fZsX6Rod0ghBZ0gg525G8JXLuOZ/BNUTX5h1Wl4LU1FSMAQFwSE5Ldz87o+x6gQSgYnneF/0Rm0EnEeougrI0ZyXhBZxSa0/ws1YvW2MxAShfCOetM3G8o0cYjLBVEPfgbEWljZy9yoqpCwaJumbM3OoOTrc+qO3ifHWrZntXSERxd/gIsyMdY0sawF3l6RP9EnBFsAby3L32EVPSCPSp7l0cSE0g+Too93n4Ws3dUNvBpBmrKWM08wO00kfnS+bZJv73xncwFLu1FIsNLFSy7ylhBVmVdDZtLMkp97JSHfEqKqmP7uIYJmsn8mrLdg==
    username: AgBHL9TJ33e5VwKeH1zb7OWdoMxbkN4CgtLOt+/CdiWPAHjZkucOqhpaBw+HbFl8cIA3vIO/12ZUFKQdgrcIs4iI84f8pS5vqMaAE3edqUGhz+ppp4nKRfI3KTOYnQwOPSPhJIpPVLq2ZY3l6nRYPImiFJi3wi23X63yHv+nH4pHTWtDH31kRyED5BOb1lMw06Jh8y+ucFcAYFVOH94WYLCNUZ3ILi9W7zCZPdtA/Z7zz32o83bzY3KMFfoQH0AUQgVZDGVQDdP7qHf2ilbsG3TB1XipEL4EOfOfPfLz9Rtt5VKhzqcHV2ylaUlj7+1JaRp6OJJwfRZZZboVD8ygFEOyLHLiJS11R0IJl8xd2fOWESOOp16WZt1dFVBnpa46v+Y264g2ihvTPT+P0eMN4ZgXl61czba3OjC69L8ujEoypffRBlYh2nXztno5nduNNwmrq3+LyrxzyBrHTj+vSfAnVL8wy2UTObLPtzkoJbl4qtA59Uls6Jsw//Yr6J8KaamePwh4DIuMqN6Txg8KlTBYp3Us131tkcdPXfuNuSAJKlCSZR9TT014uRRsiAS0SuYAJZhxvl6167wrdEqkvQixdPJ1DZYxjGvF5+nQtzela972PPRLaa/jQE6m1y/mxFow6LZlM74WtJTu5NsdsXw5C2IlbACQx3i0hLA6qz7/vVmRvZISKWh6N+3AZz91FD9uVDILJHY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: primary-credentials-metrics
      namespace: monitoring

