---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-agent-operator
      version: '>=0.2.3'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m

